import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

export const apiClient = createClient<paths>({
  baseUrl: "https://myapi.dev/v1/",
});
